[package]
name = "rust_port_scanner"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4", features = ["derive"] }
tokio = { version = "1", features = ["full"] }
ipnetwork = "0.18"
futures = "0.3"
